version: '3.8'

services:
  # ğŸ‡ Mesaj KuyruÄŸu
  rabbitmq:
    image: rabbitmq:3-management
    container_name: exam-rabbitmq
    ports:
      - '5672:5672' # Uygulama portu
      - '15672:15672' # YÃ¶netim Paneli (UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # ğŸš€ Ã–nbellek (Daha sonra kullanacaÄŸÄ±z)
  redis:
    image: redis:alpine
    container_name: exam-redis
    ports:
      - '6379:6379'
